Repository graalvm/mandrel-packaging, pull requests merged in 2020-11, with the labels that each got.

#71 Adds support for building Mandrel on Windows
  build.java
  code-formatting-rules.xml
Labels: enhancement, windows

#73 Add native-image-launcher macro
  build.java
Labels: enhancement

#76 Fix check for tags
  release-scripts/mandrel-release.java
Labels: bug

#78 Fix check for tags
  release-scripts/mandrel-release.java
Labels: bug

#79 Build native-image agent and diagnostics-agent
  .github/workflows/buildJDK.yml
  ansible/playbook.yml
  build.java
Labels: enhancement

#80 Add sha256sum and windows builds to assets
  release-scripts/mandrel-release.java
Labels: enhancement
