Repository graalvm/mandrel-packaging, pull requests merged in 2021-12, with the labels that each got.

#212 Include reporterchelper libs
  build.java
Labels: enhancement, oca-signed

#209 (master) Mx builds should use python3 to avoid issues
  build.java
Labels: oca-signed

#210 (21.3) Mx builds should use python3 to avoid issues
  build.java
Labels: oca-signed

#216 Remove more dependencies incl. TRUFFLE_ASM jar
  build.java
Labels: enhancement
