Repository graalvm/mandrel-packaging, pull requests merged in 2021-03, with the labels that each got.

#104 JDK updates, Q update
  jenkins/jobs/graal_windows_quarkus_tests.groovy
  jenkins/jobs/mandrel_20_1_linux_build.groovy
  jenkins/jobs/mandrel_20_3_linux_build.groovy
  jenkins/jobs/mandrel_20_3_windows_build.groovy
  jenkins/jobs/mandrel_21_0_linux_build.groovy
  jenkins/jobs/mandrel_21_0_windows_build.groovy
  jenkins/jobs/mandrel_linux_quarkus_container_tests.groovy
  jenkins/jobs/mandrel_linux_quarkus_tests.groovy
  jenkins/jobs/mandrel_master_linux_build.groovy
  jenkins/jobs/mandrel_master_linux_build_labsjdk.groovy
  jenkins/jobs/mandrel_master_windows_build.groovy
  jenkins/jobs/mandrel_windows_quarkus_tests.groovy
Labels: oca-signed

#106 Use mx graalvm-version instead of git describe/rev-parse
  build.java
Labels: oca-signed

#96 Updates docs on libaries and quickstart
  release-scripts/mandrel-release.java
Labels: oca-signed

#110 Quarkus 1.11.6.Final
  jenkins/jobs/graal_windows_quarkus_tests.groovy
  jenkins/jobs/mandrel_linux_quarkus_tests.groovy
  jenkins/jobs/mandrel_windows_quarkus_tests.groovy
Labels: oca-signed

#111 Increase default verbosity by not always capturing output of processes
  build.java
Labels: enhancement, oca-signed

#113 Use specific mandrel-packaging branch for 20.3 and 21.0
  jenkins/jobs/mandrel_20_3_linux_build.groovy
  jenkins/jobs/mandrel_20_3_windows_build.groovy
  jenkins/jobs/mandrel_21_0_linux_build.groovy
  jenkins/jobs/mandrel_21_0_windows_build.groovy
Labels: bug, oca-signed
