Repository graalvm/mandrel-packaging, pull requests merged in 2022-01, with the labels that each got.

#221 Delegate maven deploy to `mx`
  .github/workflows/ansible.yml
  .github/workflows/buildJDK.yml
  ansible/playbook.yml
  build.java
  resources/assembly/compiler/pom.xml
  resources/assembly/graal-sdk/pom.xml
  resources/assembly/jvmti-agent-base/pom.xml
  resources/assembly/library-support/pom.xml
  resources/assembly/objectfile/pom.xml
  resources/assembly/pointsto/pom.xml
  resources/assembly/svm-agent/pom.xml
  resources/assembly/svm-configure/pom.xml
  resources/assembly/svm-diagnostics-agent/pom.xml
  resources/assembly/svm-driver/pom.xml
  resources/assembly/svm/pom.xml
  resources/assembly/truffle-api/pom.xml
  resources/release/compiler/pom.xml
  resources/release/graal-sdk/pom.xml
  resources/release/jvmti-agent-base/pom.xml
  resources/release/library-support/pom.xml
  resources/release/objectfile/pom.xml
  resources/release/pointsto/pom.xml
  resources/release/svm-agent/pom.xml
  resources/release/svm-configure/pom.xml
  resources/release/svm-diagnostics-agent/pom.xml
  resources/release/svm-driver/pom.xml
  resources/release/svm/pom.xml
  resources/release/truffle-api/pom.xml
Labels: enhancement, oca-signed

#219 Generate, install, and deploy mandrel-build-wrapper with resources
  build.java
  resources/mandrel-packaging-wrapper.patch
Labels: oca-signed

#223 Move native-image launcher patching to 2nd step in 2 step builds
  build.java
Labels: bug

#224 Add Specification-Version and Implementation-Version to Manifest
  .github/workflows/buildJDK.yml
  build.java
Labels: bug, oca-signed

#234 Updated Prerequisites text to be on par with the main doc
  release-scripts/mandrel-release.java
Labels: oca-signed

#232 Release-script: Make upstream tag optional when releasing
  release-scripts/mandrel-release.java
Labels: enhancement, oca-signed
